package com.example.mvvm.model

import android.app.Application

class StringValues:Application() {
     val ACCESS_TOKEN_KEY: String ="Authorization"
     val ACCOUNT: String ="account"
     val ACTIVE: String ="active"
     val ADDRESS: String ="address"
     val AVATAR: String ="avatar"
     val CODE: String ="code"
     val CONTENT_TYPE_KEY: String ="Content-Type"
     val CONTENT_TYPE_VALUE: String ="application/json; charset=utf-8"
     val DATA: String ="data"
     val DATABASE: String ="data-list.db"
     val DOB: String ="dob"
     val EMAIL: String ="email"
     val FEMALE: String ="female"
     val FIELD: String ="field"
     val FIRST_NAME: String ="first_name"
     val GENDER: String ="gender"
     val HOME: String ="Home"
     val HREF: String ="href"
     val ID: String ="id"
     val INACTIVE: String ="inactive"
     val LAST_NAME: String ="last_name"
     val LINKS: String ="_links"
     val MALE: String ="male"
     val MESSAGE: String ="message"
     val META: String ="_meta"
     val NOT_FOUND: String ="not found"
     val PHONE: String ="phone"
     val PREFERENCE_NAME: String ="name"
     val PREFERENCE_PASSWORD: String ="password"
     val REMEMBER_ACCOUNT: String ="account"
     val REMEMBER_KEY: String ="autoLogin"
     val REMEMBER_TOGGLE: String ="remember"
     val RESULT: String ="result"
     val SELECTED_ITEM: String ="selected_item"
     val SELECTED_ITEM_POSITION: String ="position"
     val STATUS: String ="status"
     val SUCCESS: String ="success"
     val USER_DETAILS_URL: String ="https://gorest.co.in/public-api/users/"
     val USERS_PAGE_URL: String ="https://gorest.co.in/public-api/users?page="
     val WEBSITE: String ="website"
     val passwordRegex: String ="^=?=.*?[A-Z])=?=.*?[a-z])=?=.*?[0-9]).{8,}$"
     val emailRegex: String ="[A-Z0-9a-z]+@[A-Za-z0-9]+\\.[A-Za-z]{2,64}"
     val accessToken: String = "Bearer ECrl5oVQGWxkatlCGzXkIigkiazt3BBtW0SI"
}
