package com.example.mvvm.model

import android.app.Application

class StringValues:Application() {
     val ACCESS_TOKEN_KEY="Authorization"
     val ACCOUNT="account"
     val ACTIVE="active"
     val ADDRESS="address"
     val AVATAR="avatar"
     val CODE="code"
     val CONTENT_TYPE_KEY="Content-Type"
     val CONTENT_TYPE_VALUE="application/json; charset=utf-8"
     val DATA="data"
     val DATABASE="data-list.db"
     val DOB="dob"
     val EMAIL="email"
     val FEMALE="female"
     val FIELD="field"
     val FIRST_NAME="first_name"
     val GENDER="gender"
     val HOME="Home"
     val HREF="href"
     val ID="id"
     val INACTIVE="inactive"
     val LAST_NAME="last_name"
     val LINKS="_links"
     val MALE="male"
     val MESSAGE="message"
     val META="_meta"
     val NOT_FOUND="not found"
     val PHONE="phone"
     val PREFERENCE_NAME="name"
     val PREFERENCE_PASSWORD="password"
     val REMEMBER_ACCOUNT="account"
     val REMEMBER_KEY="autoLogin"
     val REMEMBER_TOGGLE="remember"
     val RESULT="result"
     val SELECTED_ITEM="selected_item"
     val SELECTED_ITEM_POSITION="position"
     val STATUS="status"
     val SUCCESS="success"
     val USER_DETAILS_URL="https://gorest.co.in/public-api/users/"
     val USERS_PAGE_URL="https://gorest.co.in/public-api/users?page="
     val WEBSITE="website"
     val passwordRegex ="^=?=.*?[A-Z])=?=.*?[a-z])=?=.*?[0-9]).{8,}$"
     val emailRegex="[A-Z0-9a-z]+@[A-Za-z0-9]+\\.[A-Za-z]{2,64}"
     val accessToken = "Bearer ECrl5oVQGWxkatlCGzXkIigkiazt3BBtW0SI"
}